### ISSUE TITLE
Error Code

### ISSUE THREAD

**Issue by DiscrimIsPog** [kgsensei/BlooketHack#12]
I get this error when running: 

`Please Wait, If you get stuck on this for too long please report it.

Traceback (most recent call last):
  File "D:\Coding\schoolcheats\flood.py", line 129, in <module>
    jsondata = jsondata.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte`

**Comment by Dumnersm580** [comment]
can you fix it yet

**Comment by kgsensei** [comment]
I have not, turns out the entire hack broke. Since the person who volunteered to keep the project functioning has not, I will be taking control over development again. I plan to make it even better than before by the end of this weekend. Please stay patient for a little longer.

Sorry for not getting back to you guys sooner.

**Comment by kgsensei** [comment]
Alright, what language is your blooket set?
Are there any special characters? 
What os are you on?

That should be all I need to know for now.

**Comment by kgsensei** [comment]
Alright, you can try again now and see if it works.
